/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthEditor: typeof import('./src/components/AuthEditor.vue')['default']
    BodyDocsViewer: typeof import('./src/components/BodyDocsViewer.vue')['default']
    CaseBar: typeof import('./src/components/CaseBar.vue')['default']
    CodeEditor: typeof import('./src/components/CodeEditor.vue')['default']
    DocPreview: typeof import('./src/components/DocPreview.vue')['default']
    EnvManager: typeof import('./src/components/EnvManager.vue')['default']
    HeadersEditor: typeof import('./src/components/HeadersEditor.vue')['default']
    JsonSchemaTable: typeof import('./src/components/JsonSchemaTable.vue')['default']
    MainLayout: typeof import('./src/components/MainLayout.vue')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NInput: typeof import('naive-ui')['NInput']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NSelect: typeof import('naive-ui')['NSelect']
    NTooltip: typeof import('naive-ui')['NTooltip']
    PathVariablesEditor: typeof import('./src/components/PathVariablesEditor.vue')['default']
    ProjectSettingsModal: typeof import('./src/components/ProjectSettingsModal.vue')['default']
    QueryParamsEditor: typeof import('./src/components/QueryParamsEditor.vue')['default']
    RequestMetaModal: typeof import('./src/components/RequestMetaModal.vue')['default']
    ResponsePanel: typeof import('./src/components/ResponsePanel.vue')['default']
    SettingsModal: typeof import('./src/components/SettingsModal.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    WebSocketPanel: typeof import('./src/components/WebSocketPanel.vue')['default']
  }
}
