/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CaseBar: typeof import('./src/components/CaseBar.vue')['default']
    CodeEditor: typeof import('./src/components/CodeEditor.vue')['default']
    EnvManager: typeof import('./src/components/EnvManager.vue')['default']
    MainLayout: typeof import('./src/components/MainLayout.vue')['default']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    RequestPanel: typeof import('./src/components/RequestPanel.vue')['default']
    ResponsePanel: typeof import('./src/components/ResponsePanel.vue')['default']
    SettingsModal: typeof import('./src/components/SettingsModal.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
  }
}
