// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function BuildCurl(arg1:domain.HttpRequest):Promise<string>;

export function GetFileList(arg1:string):Promise<Array<string>>;

export function LoadRequest(arg1:string,arg2:string):Promise<domain.HttpRequest>;

export function ParseCurl(arg1:string):Promise<domain.HttpRequest>;

export function SaveRequest(arg1:string,arg2:string,arg3:domain.HttpRequest):Promise<string>;

export function SelectWorkDir():Promise<string>;

export function SendRequest(arg1:domain.HttpRequest):Promise<domain.HttpResponse>;
