// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildCurl(arg1) {
  return window['go']['main']['App']['BuildCurl'](arg1);
}

export function GetFileList(arg1) {
  return window['go']['main']['App']['GetFileList'](arg1);
}

export function GetFileSummaries(arg1) {
  return window['go']['main']['App']['GetFileSummaries'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function LoadConfig(arg1, arg2) {
  return window['go']['main']['App']['LoadConfig'](arg1, arg2);
}

export function LoadRequest(arg1, arg2) {
  return window['go']['main']['App']['LoadRequest'](arg1, arg2);
}

export function ParseCurl(arg1) {
  return window['go']['main']['App']['ParseCurl'](arg1);
}

export function SaveConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2, arg3);
}

export function SaveRequest(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveRequest'](arg1, arg2, arg3);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectWorkDir() {
  return window['go']['main']['App']['SelectWorkDir']();
}

export function SendRequest(arg1) {
  return window['go']['main']['App']['SendRequest'](arg1);
}

export function SyncSwagger(arg1, arg2) {
  return window['go']['main']['App']['SyncSwagger'](arg1, arg2);
}
