// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {storage} from '../models';
import {history} from '../models';
import {main} from '../models';

export function BuildCurl(arg1:domain.HttpRequest):Promise<string>;

export function ClearHistory(arg1:string):Promise<string>;

export function DeleteFile(arg1:string,arg2:string):Promise<void>;

export function GetEnvConfig(arg1:string):Promise<storage.EnvConfig>;

export function GetFileList(arg1:string):Promise<Array<string>>;

export function GetFileSummaries(arg1:string):Promise<Array<storage.FileSummary>>;

export function GetHistoryList(arg1:string):Promise<Array<history.HistoryEntry>>;

export function GetLastOpenedProject():Promise<string>;

export function GetProjectConfig(arg1:string):Promise<storage.ProjectConfig>;

export function GetRecentProjects():Promise<Array<string>>;

export function GetSettings():Promise<main.AppConfig>;

export function LoadConfig(arg1:string,arg2:string):Promise<string>;

export function LoadRequest(arg1:string,arg2:string):Promise<domain.RequestFile>;

export function OpenProject(arg1:string):Promise<void>;

export function ParseCurl(arg1:string):Promise<domain.HttpRequest>;

export function PurgeDeletedFiles(arg1:string):Promise<string>;

export function RemoveProject(arg1:string):Promise<void>;

export function SaveConfig(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SaveFullRequest(arg1:string,arg2:string,arg3:domain.RequestFile):Promise<string>;

export function SaveProjectConfig(arg1:string,arg2:string):Promise<string>;

export function SaveRequest(arg1:string,arg2:string,arg3:domain.HttpRequest):Promise<string>;

export function SaveSettings(arg1:main.AppConfig):Promise<string>;

export function SelectWorkDir():Promise<string>;

export function SendRequest(arg1:domain.HttpRequest,arg2:string):Promise<domain.HttpResponse>;

export function SyncSwagger(arg1:string,arg2:string):Promise<string>;

export function WsConnect(arg1:string,arg2:string,arg3:Record<string, string>):Promise<string>;

export function WsDisconnect(arg1:string):Promise<string>;

export function WsSend(arg1:string,arg2:string):Promise<string>;
