// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ParseCurl(arg1:string):Promise<main.HttpRequest>;

export function SendRequest(arg1:main.HttpRequest):Promise<main.HttpResponse>;
